export const PROVINCE_API_CALL_REQUEST = "PROVINCE_API_CALL_REQUEST"
export const PROVINCE_API_CALL_SUCCESS = "PROVINCE_API_CALL_SUCCESS"
export const PROVINCE_API_CALL_FAILURE = "PROVINCE_API_CALL_FAILURE"

export const DISTRICT_API_CALL_REQUEST = "DISTRICT_API_CALL_REQUEST"
export const DISTRICT_API_CALL_SUCCESS = "DISTRICT_API_CALL_SUCCESS"
export const DISTRICT_API_CALL_FAILURE = "DISTRICT_API_CALL_FAILURE"

export const AUTHENTICATE_API_CALL_REQUEST = "AUTHENTICATE_API_CALL_REQUEST"
export const AUTHENTICATE_API_CALL_SUCCESS = "AUTHENTICATE_API_CALL_SUCCESS"
export const AUTHENTICATE_API_CALL_FAILURE = "AUTHENTICATE_API_CALL_FAILURE"